import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import companiesRouter from "./companies";
import contactsRouter from "./contacts";
import leadsRouter from "./leads";
import opportunitiesRouter from "./opportunities";
import activitiesRouter from "./activities";
import notesRouter from "./notes";
import tasksRouter from "./tasks";
import notificationsRouter from "./notifications";
import pipelinesRouter from "./pipelines";
import funnelRouter from "./funnel";
import campaignsRouter from "./campaigns";
import workflowsRouter from "./workflows";
import scoringRouter from "./scoring";
import kpisRouter from "./kpis";
import conversationsRouter from "./conversations";
import templatesRouter from "./templates";
import integrationsRouter from "./integrations";
import dashboardRouter from "./dashboard";
import settingsRouter from "./settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(companiesRouter);
router.use(contactsRouter);
router.use(leadsRouter);
router.use(opportunitiesRouter);
router.use(activitiesRouter);
router.use(notesRouter);
router.use(tasksRouter);
router.use(notificationsRouter);
router.use(pipelinesRouter);
router.use(funnelRouter);
router.use(campaignsRouter);
router.use(workflowsRouter);
router.use(scoringRouter);
router.use(kpisRouter);
router.use(conversationsRouter);
router.use(templatesRouter);
router.use(integrationsRouter);
router.use(dashboardRouter);
router.use(settingsRouter);

export default router;
